version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - auth_db
    volumes:
      - go-modules:/go/pkg/mod
      - ./uploads:/uploads
    restart: unless-stopped
    networks:
      - app-network

  auth_db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - auth-db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth-db_data:
  go-modules:

networks:
  app-network:
    driver: bridge
